# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

strategy:
  matrix:           # 配置 travis-ci 系统变量
    include:
      - os: linux   # 指定构建环境的系统类型
      - compiler: gcc  # 指定编译器

steps:
- script: |
    make
  displayName: 'make'
